---
title: "Compute Canvas Grades"
author: "Dr K"
date: "Year 2019"
output:
  html_document:
    df_print: paged
  word_document: default
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
alldata <- read.csv(file = "2018-12-07T1451_Grades-2018-70837-MATH115.csv")
#names(alldata)
```

# Use dplyr to cut up the data

```{r}
#canvas puts summary crap in download that ends in .Points and .Score so it gets removed with select(-ends_with) 
Dcamp <- select(alldata,Student,contains("DataCamp.")) %>% select(-ends_with(".Points"))%>% select(-ends_with(".Score"))
```



```{r}
#canvas has row 1 as points possible so you need to pick the second highest point to get the highest student score
require(purrr)
#summary(Dcamp)
Dcamp[is.na(Dcamp)] <- 0
#now sum rows
Dcamp$Dcamp_sum <-rowSums(Dcamp[,2:ncol(Dcamp)]) 
#(Dcamp)
Dcamp$DcampNorm <- Dcamp$Dcamp_sum/sort(Dcamp$Dcamp_sum,decreasing = TRUE)[[2]]
``` 

```{r}
Hwork <- select(alldata,Student,contains("Homework.")) 
Hwork[is.na(Hwork)] <- 0
Hwork$Hwork_sum <-rowSums(Hwork[,2:ncol(Hwork)]) 
Hwork$HworkNorm <- Hwork$Hwork_sum/sort(Hwork$Hwork_sum,decreasing = TRUE)[[2]]
#(sort(Hwork$Hwork_sum,decreasing = TRUE)[2])
```

```{r}
Gitdat <- select(alldata,Student,contains("Git"))%>% select(-ends_with(".Points"))%>% select(-ends_with(".Score"))%>% select(-contains("DataCamp"))
Gitdat[is.na(Gitdat)] <- 0
Gitdat$Git_sum <-rowSums(Gitdat[,2:ncol(Gitdat)]) 
Gitdat$GitNorm <- Gitdat$Git_sum/sort(Gitdat$Git_sum,decreasing = TRUE)[[2]]
```
```{r}
#had to pick the appropriate columns -- next time put appropriate name in canvas assignment name and retrieve with select command
writeup <- alldata[,c(1,14,19,21,22,25,26,27,41,49,50,51)]
writeup[is.na(writeup)] <- 0
writeup$Writeup_sum <-rowSums(writeup[,2:ncol(writeup)])
writeup$WriteupNorm <- writeup$Writeup_sum/sort(writeup$Writeup_sum,decreasing = TRUE)[[2]]
```

```{r}
Final <- select(alldata,Student,starts_with("fin"))%>%select(-ends_with(".Points"))%>% select(-ends_with(".Score"))
Final[is.na(Final)] <- 0


Final$FinalNorm <- Final[,2]/sort(Final[,2],decreasing = TRUE)[[2]]
```

  
######################################################

#Now create a dataframe with just the normed data

```{r}
one <- select(Dcamp,Student,DcampNorm)
two <- select(Hwork,HworkNorm)
three <- select(Gitdat,GitNorm)
four <- select(writeup,WriteupNorm)
five <- select(Final,FinalNorm)
rollup <- cbind(one,two,three,four,five)
```


```{r}
rollup$grade <- rollup$HworkNorm*25 + rollup$DcampNorm*20 + rollup$WriteupNorm*20 + rollup$GitNorm*10 + rollup$FinalNorm*25
rollup$grade2 <- rollup$HworkNorm*25 + rollup$DcampNorm*20 + rollup$WriteupNorm*25 + rollup$GitNorm*5 + rollup$FinalNorm*25
print(rollup)[,c(1,7,8)]
write.csv(rollup,file="PMGrades_CRN70837.csv",sep=",")
```
  

